### ISSUE TITLE
The plugin does not work properly if we change the destination of the homebrew installation

### ISSUE THREAD

**Issue by intptr-t** [unixorn/lima-xbar-plugin#28]
If we have changed the installation destination of homebrew, unable to find limactl.
Is there any better solution?

### Exception

```
exit status 1: Traceback (most recent call last):
  File "./lima-plugin", line 600, in <module>
    main()
  File "./lima-plugin”, line 578, in main
    xbarMenu()
  File "./lima-plugin", line 556, in xbarMenu
    vms = listVMs()  
  File "./lima-plugin”, line 256, in listVMs
    vmRaw = subprocess.run(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'limactl'
```

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/9898058/155377152-3462b460-fbae-4b35-be54-ee4930ebc848.png">

### xbar or swiftbar starts the plugin with PATH as follows:
`PATH=/usr/bin:/bin:/usr/sbin:/sbin`

My installation directory of homebrew:
```
% brew --prefix
/Users/${USER}/homebrew
```
lima-xbar-plugin cannot call limactl because brew --prefix cannot be used.

## Temporary workaround

Add the `homebrew/bin` path directly to [extrapaths](https://github.com/unixorn/lima-xbar-plugin/blob/main/lima-plugin#L281)

```python
extrapaths = ["/usr/local/bin", "/opt/homebrew/bin", "/opt/local/bin", "/Users/${USER}/homebrew/bin"]
```

## Expected results
The path of homebrew/bin is automatically resolved and limactl can be called.
Then xbar or swiftbar will not generate any errors.

**Comment by unixorn** [comment]
Where is `brew` itself installed on your installation? The code needs to be able to run `brew --prefix` to find the `bin` directory.

**Comment by intptr-t** [comment]
I followed the instructions [Alternative Installs](https://github.com/Homebrew/brew/blob/master/docs/Installation.md#alternative-installs) to install it.

And I have installed the brew itself in the following directory

```
% which brew
/Users/${USER}/homebrew/bin/brew
```

**Comment by unixorn** [comment]
Custom `brew` locations are going to be a hassle to deal with automatically. I'll have to add a menu item that lets you set/unset the location of `brew`, but it's going to have to be a manual process - I can't anticipate all the locations people might stash their `brew` install in.

That said, sticking it in the home directory seems like it's the most likely alternate location, so I'll add that as one of the default places to search.

This would be a lot easier if macOS gui apps picked up stuff like `$PATH` from the shell's login environment, but I understand why they don't go that route.
