### ISSUE TITLE
Suggestion: use `limactl list --json`

### ISSUE THREAD

**Issue by AkihiroSuda** [unixorn/lima-xbar-plugin#4]
First, thanks a lot for working on this

https://github.com/unixorn/lima-xbar-plugin/blob/e32889db0b1b7b1d9c8697b75b5be5e6242bddcb/lima-plugin#L71

The grep above doesn't seem robust, and will probably break soon with a future version of Lima.
I'd suggest using `limactl list --json` and use `jq` for parsing JSON.

```console
$ limactl list --json  | jq .
{
  "name": "default",
  "status": "Running",
  "dir": "/Users/suda/.lima/default",
  "arch": "x86_64",
  "sshLocalPort": 60022,
  "hostAgentPID": 1968,
  "qemuPID": 1972
}
```

**Comment by unixorn** [comment]
Thanks for the tip, I'll update accordingly, then work on https://github.com/lima-vm/lima/issues/253
